### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by xenithorb** [mmk2410/atom-oss-license#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: "Fedora release
**Thrown From**: [atom-oss-license](https://github.com/mmk2410/atom-oss-license) package 1.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At /home/xenith/git/dotfiles/.atom/packages/atom-oss-license/lib/atom-oss-license.coffee:285

TypeError: Cannot read property 'buffer' of undefined
    at Object.hasCopyright (/packages/atom-oss-license/lib/atom-oss-license.coffee:285:41)
    at Object.addLicense (/packages/atom-oss-license/lib/atom-oss-license.coffee:325:13)
    at Object.mit (/packages/atom-oss-license/lib/atom-oss-license.coffee:242:6)
    at /packages/atom-oss-license/lib/atom-oss-license.coffee:59:27)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:143:35)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -4:04.7.0 core:backspace (input.hidden-input)
 14x -4:00.5.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-arc-ui.teletype-Authenticated)
  3x -2:35.6.0 core:confirm (input.hidden-input)
     -1:24.6.0 core:backspace (input.hidden-input)
     -1:23.9.0 core:confirm (input.hidden-input)
     -0:39.4.0 project-manager:list-projects (div.tool-panel.tree-view)
  3x -0:18.9.0 core:backspace (input.hidden-input)
     -0:17.7.0 editor:consolidate-selections (input.hidden-input)
     -0:17.7.0 core:cancel (input.hidden-input)
     -0:17.5.0 tree-view:unfocus (div.tool-panel.tree-view)
     -0:16.8.0 command-palette:toggle (div.panels-item)
 17x -0:14.7.0 core:move-down (input.hidden-input)
 18x -0:12.2.0 core:move-up (input.hidden-input)
     -0:09.3.0 core:move-down (input.hidden-input)
     -0:08.6.0 core:confirm (input.hidden-input)
     -0:08.6.0 License: MIT (div.panels-item)
```

### Non-Core Packages

```
ansible-galaxy 0.2.1 
ansible-vault 0.6.9 
arc-ui 0.1.7 
atom-beautify 0.30.9 
atom-ide-ui 0.8.1 
atom-jinja2 0.6.0 
atom-oss-license 1.1.2 
autocomplete-ansible 0.1.15 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
docker 0.8.0 
file-types 0.5.5 
git-plus 7.10.0 
ide-docker 0.0.2 
ide-html 0.4.1 
ide-json 0.2.0 
ide-python 0.7.0 
ide-yaml 0.4.2 
intentions 1.1.5 
jslint 1.5.1 
json-path-finder 0.1.9 
language-ansible 0.2.2 
language-cisco 1.4.0 
language-docker 1.1.8 
language-dotfiles 1.1.0 
language-markdown 0.25.1 
language-nginx 0.8.0 
language-rpm-spec 0.15.0 
linter 2.2.0 
linter-ansible-linting 1.3.1 
linter-ansible-syntax 1.2.0 
linter-docker 0.3.0 
linter-flake8 2.3.0 
linter-haproxy 0.2.2 
linter-js-yaml 1.2.8 
linter-jsonlint 1.3.0 
linter-markdown 5.2.0 
linter-pycodestyle 2.1.3 
linter-ruby 1.2.6 
linter-shellcheck 1.4.6 
linter-ui-default 1.6.10 
linter-write-good 0.9.0 
markdown-themeable-pdf 1.2.0 
markdown-writer 2.7.3 
maximize-active-pane 0.1.0 
maximize-panes 0.2.0 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-linter 2.1.3 
minimap-split-diff 0.3.7 
package-sync 1.1.0 
pandoc-convert 1.1.1 
pdf-view 0.65.0 
platformio-ide-terminal 2.8.0 
project-manager 3.3.5 
script 3.17.3 
split-diff 1.5.2 
sync-settings 0.8.3 
teletype 0.7.0 
term3 0.22.1 
tool-bar 1.1.6 
tool-bar-atom 1.7.0 
tool-bar-markdown-writer 0.3.1 
tree-view-git-status 1.4.0 
```

**Comment by lexfrei** [comment]
Same.
